In [1]:
import numpy as np

In [2]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [3]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [4]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [5]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr = np.arange(3,30,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr = np.linspace(3,6,3)
arr

array([3. , 4.5, 6. ])

In [8]:
arr.shape

(3,)

In [9]:
arr = arr.reshape(3,1)
arr

array([[3. ],
       [4.5],
       [6. ]])

In [10]:
np.random.rand(3)

array([0.60118714, 0.28425492, 0.58364212])

In [11]:
np.random.randn(4)

array([ 0.96735292, -2.57567027, -0.2208791 ,  1.52423673])

In [12]:
np.random.randint(4,100)

69

In [13]:
np.random.randint(4,100,4)

array([34, 27, 78, 17])

In [14]:
np.random.seed(4) # seed freeze the random number
np.random.randint(4,100)

50

In [15]:
arr = np.random.randint(1,34,6)
arr

array([ 6,  2, 24,  9, 10, 31])

In [16]:
arr.min()

2

In [17]:
arr.max()

31

In [18]:
arr.argmax() # Gives index

5

In [19]:
arr.argmin() # Gives index

1

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[:4]

array([0, 1, 2, 3])

In [22]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [23]:
arr2 = arr.copy() # if not copy then it will change original data
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr_2d = np.array([[3,5,7],[4,6,8],[1,9,10]])
arr_2d

array([[ 3,  5,  7],
       [ 4,  6,  8],
       [ 1,  9, 10]])

In [25]:
arr_2d[2][2]

10

In [26]:
arr_2d[2,2]

10

In [27]:
# for getting rows
arr_2d[:2]

array([[3, 5, 7],
       [4, 6, 8]])

In [28]:
arr_2d[:2,:1]

array([[3],
       [4]])

In [29]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[arr > 4]

array([5, 6, 7, 8, 9])

In [31]:
arr[arr % 4 == 0]

array([4, 8])

In [32]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
 1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [37]:
arr/0

/home/naitik147896/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [38]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [39]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [40]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [41]:
np.sum(arr)

45

In [42]:
arr_2d = np.array([[3,5,7],[4,6,8],[1,9,10]])
arr_2d

array([[ 3,  5,  7],
       [ 4,  6,  8],
       [ 1,  9, 10]])

In [43]:
np.sum(arr_2d)

53

In [44]:
np.sum(arr_2d,axis=0) # axis 0 means vertical axis

array([ 8, 20, 25])

In [45]:
np.sum(arr_2d,axis=1) # axis 0 means horizontal axis

array([15, 18, 20])