In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.dtype

dtype('int64')

In [6]:
torch.from_numpy(arr) # convert from numpy to tensor

tensor([1, 2, 3, 4, 5])

In [7]:
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5])

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr) # convert to tensor

tensor([1, 2, 3, 4, 5])

In [10]:
x.dtype

torch.int64

In [12]:
arr2d = np.arange(0,12)
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
torch.from_numpy(arr2d)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [15]:
x2 = torch.tensor(arr2d) # It convert and copoes into x2 so no linking between arr2d and x2
x2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
torch.tensor(arr) # Small tensor converts into int

tensor([1, 2, 3, 4, 5])

In [18]:
torch.Tensor(arr) # Capital Tensor converts into float

tensor([1., 2., 3., 4., 5.])

In [19]:
torch.empty(3,4) # Random number block

tensor([[-4.2151e+28,  3.0817e-41, -4.0156e+28,  3.0817e-41],
        [ 1.1210e-43,  0.0000e+00,  8.9683e-44,  0.0000e+00],
        [-9.3248e+27,  3.0817e-41,  1.7748e+28,  1.8176e+31]])

In [20]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [25]:
torch.linspace(0,1,10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [26]:
torch.rand(4,3)

tensor([[0.2062, 0.7941, 0.6042],
        [0.6305, 0.1826, 0.8395],
        [0.6937, 0.6143, 0.5883],
        [0.5106, 0.9711, 0.8426]])

In [27]:
torch.randn(4,3)

tensor([[-0.7927, -0.8133,  0.2601],
        [ 0.6495,  0.2953,  0.1641],
        [-0.0680, -0.8074,  0.4763],
        [-2.3968, -0.0039,  0.0442]])

In [32]:
torch.randint(0,4,(3,4))

tensor([[2, 1, 2, 0],
        [1, 0, 0, 0],
        [0, 0, 2, 1]])

In [41]:
x

tensor([1, 2, 3, 4, 5])

In [53]:
x = x.type(dtype=torch.float)

In [54]:
x.dtype

torch.float32

In [55]:
torch.randn_like(x) # Like only works for float datatype

tensor([-0.5349, -1.8432,  0.0131,  0.1445,  0.3210])

In [56]:
torch.rand_like(x)

tensor([0.2498, 0.7547, 0.3942, 0.6949, 0.9016])

In [59]:
torch.randint_like(x,0,4)

tensor([3., 1., 0., 3., 2.])

In [63]:
torch.manual_seed(42) # Remember to get same numbers seed and rand needs in once cell
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [64]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [65]:
x

tensor([1., 2., 3., 4., 5.])

In [66]:
x2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [67]:
x2[1,1]

tensor(4)

In [68]:
x2[:,2]

tensor([ 2,  5,  8, 11])

In [69]:
x2[:,2].reshape(-1,1) # Transpose

tensor([[ 2],
        [ 5],
        [ 8],
        [11]])

In [70]:
x2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [73]:
a = torch.Tensor([1,2,3])
a

tensor([1., 2., 3.])

In [74]:
b = torch.Tensor([4,5,6])
b

tensor([4., 5., 6.])

In [75]:
a + b

tensor([5., 7., 9.])

In [77]:
torch.add(a,b)

tensor([5., 7., 9.])

In [78]:
a.mul(b) #  a * b

tensor([ 4., 10., 18.])

In [80]:
a

tensor([1., 2., 3.])

In [81]:
a.mul_(b) #  a = a * b

tensor([ 4., 10., 18.])

In [82]:
a

tensor([ 4., 10., 18.])

In [83]:
a * b # element wise multi

tensor([ 16.,  50., 108.])

In [84]:
a.dot(b)

tensor(174.)

In [94]:
a = a.reshape(1,3)

In [90]:
b = b.reshape(-1,1)
b

tensor([[4.],
        [5.],
        [6.]])

In [95]:
a.shape

torch.Size([1, 3])

In [92]:
b.shape

torch.Size([3, 1])

In [96]:
torch.mm(a,b) # Matrix multiplication

tensor([[174.]])